{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sample-controller.fullname" .}}
  namespace: {{ .Values.namespace.name}}
  labels:
  {{- include "sample-controller.labels" . | nindent 4}}
rules:
  - verbs:
      - get
      - watch
      - update
      - list
    apiGroups:
      - ""
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sample-controller.fullname" .}}
  namespace: {{.Values.namespace.name}}
  labels:
  {{- include "sample-controller.labels" . | nindent 4}}
subjects:
  - kind: ServiceAccount
    name: {{ include "sample-controller.serviceAccountName" .}}
    namespace: {{.Values.namespace.name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sample-controller.fullname" .}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sample-controller.serviceAccountName" . }}
  namespace: {{.Values.namespace.name}}
  labels:
  {{- include "sample-controller.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: controller-leader-election
  namespace: {{ .Values.namespace.name}}
  labels:
  {{- include "sample-controller.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - create
      - update
    apiGroups:
      - ""
    resources:
      - configmaps
  - verbs:
      - get
      - create
      - update
    apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
  - verbs:
      - "*"
    apiGroups:
      - ""
    resources:
      - events
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller-leader-election-binding
  namespace: {{.Values.namespace.name}}
  labels:
  {{- include "sample-controller.labels" . | nindent 4}}
subjects:
  - kind: ServiceAccount
    name: {{ include "sample-controller.serviceAccountName" .}}
    namespace: {{ .Values.namespace.name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: controller-leader-election
  {{- end}}