apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-controller.fullname" . }}
  labels:
    {{- include "sample-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
      name: metrics
    - port: 8081
      protocol: TCP
      name: health
  selector:
    {{- include "sample-controller.selectorLabels" . | nindent 4 }}
